/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.IRMAmainController;
import Controllers.LoginController;
import Interfaces.InformationSelection;

/**
 *
 * @author Chronos
 */
public class ManagerView extends javax.swing.JFrame {

    /**
     * Creates new form ManagerView
     */
    public ManagerView() {
        initComponents();
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddC = new javax.swing.JButton();
        btnModC = new javax.swing.JButton();
        btnDelC = new javax.swing.JButton();
        btnAddE = new javax.swing.JButton();
        btnModE = new javax.swing.JButton();
        btnDelE = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddC.setText("Add New Customer");
        btnAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCActionPerformed(evt);
            }
        });

        btnModC.setText("Modify Customer");
        btnModC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCActionPerformed(evt);
            }
        });

        btnDelC.setText("Delete Customer");
        btnDelC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCActionPerformed(evt);
            }
        });

        btnAddE.setText("Add New Employee");
        btnAddE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEActionPerformed(evt);
            }
        });

        btnModE.setText("Modify Employee");
        btnModE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModEActionPerformed(evt);
            }
        });

        btnDelE.setText("Delete Employee");
        btnDelE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEActionPerformed(evt);
            }
        });

        btnLogout.setForeground(new java.awt.Color(204, 0, 0));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblError.setText("Error: Generic Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(lblError))
                    .addComponent(btnLogout))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddC)
                .addGap(18, 18, 18)
                .addComponent(btnModC)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDelC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblError)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddE)
                .addGap(18, 18, 18)
                .addComponent(btnModE)
                .addGap(18, 18, 18)
                .addComponent(btnDelE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginView logv = new LoginView();
      logv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCActionPerformed
        // TODO add your handling code here:
        Controllers.IRMAmainController.MakeInfoView();
        IRMAmainController.setChoice(InformationSelection.MANAGERADDC);
    }//GEN-LAST:event_btnAddCActionPerformed

    private void btnModCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCActionPerformed
        // TODO add your handling code here:
        Controllers.IRMAmainController.MakeInfoView();
        IRMAmainController.setChoice(InformationSelection.MANAGERMODC);
    }//GEN-LAST:event_btnModCActionPerformed

    private void btnDelCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCActionPerformed
        // TODO add your handling code here:
        Controllers.IRMAmainController.MakeInfoView();
        IRMAmainController.setChoice(InformationSelection.MANAGERDELC);
    }//GEN-LAST:event_btnDelCActionPerformed

    private void btnAddEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEActionPerformed
        // TODO add your handling code here:
        Controllers.IRMAmainController.MakeInfoView();
        IRMAmainController.setChoice(InformationSelection.MANAGERADDE);
    }//GEN-LAST:event_btnAddEActionPerformed

    private void btnModEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModEActionPerformed
        // TODO add your handling code here:
        Controllers.IRMAmainController.MakeInfoView();
        IRMAmainController.setChoice(InformationSelection.MANAGERMODE);
    }//GEN-LAST:event_btnModEActionPerformed

    private void btnDelEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEActionPerformed
        // TODO add your handling code here:
        Controllers.IRMAmainController.MakeInfoView();
        IRMAmainController.setChoice(InformationSelection.MANAGERDELE);
    }//GEN-LAST:event_btnDelEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddC;
    private javax.swing.JButton btnAddE;
    private javax.swing.JButton btnDelC;
    private javax.swing.JButton btnDelE;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModC;
    private javax.swing.JButton btnModE;
    private javax.swing.JLabel lblError;
    // End of variables declaration//GEN-END:variables
}
